[phases.setup]
nixPkgs = ["nodejs", "python3", "pip"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NPM_CONFIG_PACKAGE_MANAGER = "npm"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[[services]]
name = "frontend"
start = "npm start"

[[services]]
name = "ml-server"
start = "cd scripts && python ml-integration-example.py"

[[services]]
name = "hope-ai"
start = "cd scripts && python Hope.py" 