[phases.setup]
nixPkgs = ["nodejs", "python3", "python3Packages.pip", "python3Packages.virtualenv"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "python3 -m venv /app/venv",
  "/app/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NPM_CONFIG_PACKAGE_MANAGER = "npm"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
PATH = "/app/venv/bin:$PATH" 