services:
  # Frontend - Next.js Application
  - type: web
    name: hope-social-media-frontend
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false

  # ML Integration Server - Hate Speech Detection
  - type: web
    name: hope-ml-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scripts/ml-integration-example.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 5000

  # Hope AI Server - Psychological Support
  - type: web
    name: hope-ai-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scripts/Hope.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 5001 